This script is used to read the raw data and generate `life_quality.csv`.

In [1]:
import pandas as pd
import numpy as np

from constants import LIFE_QUALITY_DIMENSION_CSV

In [2]:
df = pd.read_csv('../raw_data/life_quality.csv')
df.replace("..", np.nan, inplace=True)

In [3]:
columns = df.columns.tolist()
# fix column years format
for i in range(4, len(columns)):
	columns[i] = columns[i][:4]
df.columns = columns
df.head(6)

,Series Name,Series Code,Country Name,Country Code,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,Canada,CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,United States,USA,NaN,3.1,NaN,2.3,NaN,2.8,NaN,2.2,NaN,2.4,NaN,3.5,NaN,3.4,NaN,NaN
2,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,Mexico,MEX,NaN,15.5,NaN,NaN,NaN,NaN,NaN,13.6,NaN,NaN,12.4,10,NaN,NaN,14.1,NaN
3,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,India,IND,NaN,47.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.7,37.9,NaN,34.7,NaN,NaN,NaN
4,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,Indonesia,IDN,NaN,NaN,40.1,NaN,NaN,39.2,NaN,NaN,36.4,NaN,NaN,NaN,NaN,30.8,NaN,NaN
5,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,"Iran, Islamic Rep.",IRN,NaN,NaN,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Replace missing value with the mean value for each country and attribute 
df[columns[4:]] = df[columns[4:]].T.fillna(df.mean(axis=1)).T
df.head(6)

C:\Users\THINK\AppData\Local\Temp/ipykernel_20908/3330549296.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df[columns[4:]] = df[columns[4:]].T.fillna(df.mean(axis=1)).T

,Series Name,Series Code,Country Name,Country Code,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,Canada,CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,United States,USA,NaN,3.1,NaN,2.3,NaN,2.8,NaN,2.2,NaN,2.4,NaN,3.5,NaN,3.4,NaN,NaN
2,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,Mexico,MEX,NaN,15.5,NaN,NaN,NaN,NaN,NaN,13.6,NaN,NaN,12.4,10,NaN,NaN,14.1,NaN
3,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,India,IND,NaN,47.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.7,37.9,NaN,34.7,NaN,NaN,NaN
4,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,Indonesia,IDN,NaN,NaN,40.1,NaN,NaN,39.2,NaN,NaN,36.4,NaN,NaN,NaN,NaN,30.8,NaN,NaN
5,"Prevalence of stunting, height for age (% of c...",SH.STA.STNT.ZS,"Iran, Islamic Rep.",IRN,NaN,NaN,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#df.rename(columns={
#    "People using at least basic drinking water services (% of population)": "basic_drinking_water_rate",
#    "People using at least basic drinking water services, rural (% of rural population)": "basic_drinking_water_rate_rural",
#    "People using at least basic drinking water services, urban (% of urban population)": "basic_drinking_water_rate_urban",
#    "People using safely managed drinking water services (% of population)": "safe_drinking_water_rate",
#    "People using safely managed drinking water services, rural (% of rural population)": "safe_drinking_water_rate_rural",
#    "People using safely managed drinking water services, urban (% of urban population)": "safe_drinking_water_rate_urban",
#    "People with basic handwashing facilities including soap and water (% of population)": "basic_handwashing_facilities_rate",
#    "People with basic handwashing facilities including soap and water, rural (% of rural population)": "basic_handwashing_facilities_rate_rural",
#    "People with basic handwashing facilities including soap and water, urban (% of urban population)": "basic_handwashing_facilities_rate_urban",
#    "People practicing open defecation (% of population)": "open_defecation_rate",
#    "People practicing open defecation, rural (% of rural population)": "open_defecation_rate_rural",
#    "People practicing open defecation, urban (% of urban population)": "open_defecation_rate_urban"
#}, inplace=True)


# rename and reorder columns
#df.rename_axis("life_quality_key", inplace=True)
#df


attributes_dic = {
    "basic_drinking_water_rate": "SH.H2O.BASW.ZS",
    "basic_drinking_water_rate_rural": "SH.H2O.BASW.RU.ZS",
    "basic_drinking_water_rate_urban": "SH.H2O.BASW.UR.ZS",
    "safe_drinking_water_rate": "SH.H2O.SMDW.ZS",
    "safe_drinking_water_rate_rural": "SH.H2O.SMDW.RU.ZS",
    "safe_drinking_water_rate_urban": "SH.H2O.SMDW.UR.ZS",
    "basic_handwashing_facilities_rate": "SH.STA.HYGN.ZS",
    "basic_handwashing_facilities_rate_rural": "SH.STA.HYGN.RU.ZS",
    "basic_handwashing_facilities_rate_urban": "SH.STA.HYGN.UR.ZS",
    "open_defecation_rate": "SH.STA.ODFC.ZS",
    "open_defecation_rate_rural": "SH.STA.ODFC.RU.ZS",
    "open_defecation_rate_urban": "SH.STA.ODFC.UR.ZS",
}

In [6]:
def transpose_attributes(dataframe, attribute):
	dataframe.drop(columns=["Series Name", "Series Code", "Country Name"], inplace=True)
	columns = dataframe.columns.tolist()
	return dataframe.melt(id_vars="Country Code", value_vars=columns[1:], var_name="Year", value_name=attribute)

In [7]:
# Transpose Attributes
attributes_df_dic = {}
for key, value in attributes_dic.items(): 
	filt = (df["Series Code"] == value)
	attribute_df = df.loc[filt].copy()
	attributes_df_dic[key] = transpose_attributes(attribute_df, key)

In [8]:
# Merge attributes together
attributes_lst_dic = list(attributes_df_dic.values())
life_quality_df = attributes_lst_dic[0] 
for i in range(1, len(attributes_lst_dic)):
	life_quality_df = pd.merge(life_quality_df, attributes_lst_dic[i], how="left", left_on=["Country Code", "Year"], right_on=["Country Code", "Year"])
life_quality_df.rename_axis("life_quality_key", inplace=True)
life_quality_df.head(30)

,Country Code,Year,basic_drinking_water_rate,basic_drinking_water_rate_rural,basic_drinking_water_rate_urban,safe_drinking_water_rate,safe_drinking_water_rate_rural,safe_drinking_water_rate_urban,basic_handwashing_facilities_rate,basic_handwashing_facilities_rate_rural,basic_handwashing_facilities_rate_urban,open_defecation_rate,open_defecation_rate_rural,open_defecation_rate_urban
life_quality_key,,,,,,,,,,,,,,
0,CAN,2005,99.23464422,98.20544302,99.48998183,98.24079534,NaN,NaN,NaN,NaN,NaN,0,0,0
1,USA,2005,98.8536874,95.51131593,99.69304221,95.23581292,NaN,96.41144911,NaN,NaN,NaN,0,0,0
2,MEX,2005,93.09668937,81.80368497,96.60292525,40.35948897,NaN,NaN,NaN,NaN,NaN,6.910224385,19.94258519,2.863955603
3,IND,2005,83.13360985,79.11866408,92.85201703,NaN,35.93492395,NaN,NaN,NaN,NaN,58.84314476,74.7755284,20.27789371
4,IDN,2005,80.02217385,70.56315099,91.15220456,NaN,NaN,NaN,NaN,NaN,NaN,25.27204,37.137722,11.31019562
5,IRN,2005,95.15500125,88.83003719,98.19230917,91.43323292,82.53148404,95.70793742,NaN,NaN,NaN,0.488579216,1.43,0.0365
6,EGY,2005,98.29760753,97.51632721,99.33211222,NaN,NaN,NaN,73.53833157,62.42338542,88.25587378,1.232966031,1.688038667,0.63039419
7,KEN,2005,51.02456418,41.09441822,86.90824272,NaN,NaN,60.30574932,NaN,NaN,NaN,15.37391052,18.89905303,2.635421007
8,NGA,2005,51.35268075,37.83069287,72.43679318,15.88227547,11.63975858,22.49740513,NaN,NaN,NaN,24.57233598,32.47784849,12.24569318
9,CAN,2006,99.23461957,98.26651823,99.47343153,98.29946776,NaN,NaN,NaN,NaN,NaN,0,0,0
10,USA,2006,98.86083682,95.51131593,99.69304221,95.24582727,NaN,96.41144911,NaN,NaN,NaN,0,0,0
11,MEX,2006,93.71099729,83.2843433,96.89332254,40.5640574,NaN,NaN,NaN,NaN,NaN,6.413280454,18.64645146,2.679589832
12,IND,2006,83.65179214,79.76593755,92.90758804,NaN,37.33337823,NaN,NaN,NaN,NaN,55.82200891,71.28437171,18.99189313
13,IDN,2006,80.92466101,71.57375745,91.5808267,NaN,NaN,NaN,69.85283043,58.38390598,82.92266464,23.86128959,35.4054939,10.70566745
14,IRN,2006,95.34517093,89.16328373,98.22245434,91.64135164,82.84110151,95.73731988,NaN,NaN,NaN,0.479089571,1.43,0.0365
15,EGY,2006,98.37929106,97.64456775,99.35033076,NaN,NaN,NaN,75.03161831,64.71734037,88.66338054,1.130610309,1.537630021,0.59267678
16,KEN,2006,51.76219866,41.82191916,86.91277753,NaN,NaN,60.10402022,NaN,NaN,NaN,14.89954899,18.39271316,2.547105316
17,NGA,2006,53.0703045,39.35668253,73.68966198,16.30025529,12.05058484,22.68992203,NaN,NaN,NaN,24.18416347,32.29160089,11.99408338
18,CAN,2007,99.23549716,98.32759343,99.45688123,98.35997369,NaN,NaN,NaN,NaN,NaN,0,0,0
19,USA,2007,98.86794461,95.51131593,99.69304221,95.2557833,NaN,96.41144911,NaN,NaN,NaN,0,0,0
20,MEX,2007,94.32032157,84.77669523,97.18390312,40.76641554,NaN,NaN,NaN,NaN,NaN,5.923779375,17.35031773,2.495224062
21,IND,2007,84.16605196,80.41277995,92.963011,NaN,38.75026338,NaN,NaN,NaN,NaN,52.8141007,67.79321501,17.70589255
22,IDN,2007,81.81767312,72.58351004,92.00953919,NaN,NaN,NaN,70.04840506,58.38390598,82.92266464,22.46825531,33.67326579,10.10113929
23,IRN,2007,95.52631238,89.49653028,98.25259951,91.83859225,83.15071899,95.76670235,NaN,NaN,NaN,0.470380177,1.43,0.0365
24,EGY,2007,98.46026211,97.77287819,99.3685509,NaN,NaN,NaN,76.51412667,67.01129531,89.07088731,1.028699537,1.387221376,0.554959371
25,KEN,2007,52.49502118,42.54725865,86.91730249,NaN,NaN,59.90217553,NaN,NaN,NaN,14.42750867,17.8863733,2.458789625
26,NGA,2007,54.79523439,40.8916024,74.95327249,16.71431554,12.4599671,22.88243893,NaN,NaN,NaN,23.79342858,32.10535328,11.74247358
27,CAN,2008,99.23607708,98.38866864,99.44033093,98.41990954,NaN,NaN,NaN,NaN,NaN,0,0,0
28,USA,2008,98.87501291,95.51131593,99.69304221,95.2656829,NaN,96.41144911,NaN,NaN,NaN,0,0,0
29,MEX,2008,94.90809059,86.21616916,97.47192479,40.96669575,NaN,NaN,NaN,NaN,NaN,5.441312933,16.054184,2.310858291

In [9]:
# Output life quality Dimension
life_quality_df.to_csv(LIFE_QUALITY_DIMENSION_CSV)